server:
  port: 8089
spring:
  application:
    name: SchoolHelp
  datasource:
    url: jdbc:mysql://localhost:3306/schoolhelp?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #设置文件上传的大小限制spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    #设置redis缓存
  data:
    redis:
      host: 192.168.0.6
      port: 6379
      database: 0
      timeout: 10s
      password: 123456
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
      repositories:
        enabled: false
  #SpringAI配置
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: always
#        chat:
#          additional-models:
#            - llama3.2
#            - qwen2.5
      chat:
        options:
          model: llama3.2:latest
          num-g-p-u: 1
      embedding: # 新增嵌入模型配置
        options:
          model: mxbai-embed-large:latest
    # 智谱
    zhipuai:
      api-key: XXX
      chat:
        enabled: true
        options:
          model: GLM-4
    # kimi
    moonshot:
      api-key: XXX
#    # openai
#    openai:
#      api-key: xai-YzPdnzgX3slr0gbRPWJR6UixaH8eC26eiIjlpPiM14Ui2Ym0edJLHNoNdGB2ihyN56EVvRIfUGKIT2FC
#      base-url: https://api.x.ai/v1/chat/completions
#      chat:
#        enabled: true
#        options:
#          model: grok-beta


#配置mybatis-plus
mybatis-plus:
  type-aliases-package: com.qys.commodity.entity
  global-config:
    db-config:
      id-type: auto #配置主键自增



